Model:
    input_shape: [224, 224, 3]
    classes: null
    weight_path: null
    load_weight_type: null
    Architecture:
        name: CLS
    Backbone:
        name: models.architectures.VGG16
        include_top: True
        weights: null