Dataset:
    data_dir: '/home/vbpo-101386/Desktop/TuNIT/Datasets/Classification/PetImages'
    annotation_dir: null
    data_info:
        label_objects: "./configs/classes.names"
        color_space: 'rgb'
        sensitive: False
        check_data: False
        load_memory: False
    data_normalizer:
        norm_type: 'sub_divide'
        norm_mean: null
        norm_std: null
    data_augmentation:
        train:
            - ResizePadded:
                flexible: True
                padding_color: 128
            - RandomFlip:
                mode: 'horizontal'
            - RandomRotate:
                angle_range: 20
                prob: 0.5
                padding_color: 128
            - LightIntensityChange:
        valid:
            - ResizePadded
                flexible: False
                padding_color: 128
        test:
    data_loader_mode: 0

Model:
    input_shape: [224, 224, 3]
    weight_path: null
    load_weight_type: null
    Architecture:
        name: CRNN
    Backbone:
        name: SVTRNet
        out_channels: 192
        attn_drop: 0.2
        proj_drop: 0.2
        drop_path_rate: 0.1
        final_drop: 0.2

Train:
    mode: 'graph'
    save_weight_path: &save_weight './saved_weights/'
    save_weight_type: &save_type 'tf'
    batch_size: 64
    epoch:
        start: 0
        end: &end_epoch 1000
        
Losses:
    - CTCLoss:
        coeff: 1

Optimizer:
    name: Adam
    learning_rate: 0.0001
    beta_1: 0.9
    beta_2: 0.999
    global_clipnorm: 5.0

Metrics:
    - CTCCharacterAccuracy:
        vocabulary: *char
    - CTCWordAccuracy:
        vocabulary: *char

Callbacks:
    - MetricHistory:
        save_best: True
        save_format: *save_type
    - LossHistory:
        save_best: False
        save_format: *save_type
    # - ModelCheckpoint:
    #     extend_path: 'weights/checkpoint_{epoch:04d}/saved_str_weights'
    #     monitor: 'val_loss'
    #     save_weights_only: True
    #     save_freq: 'epoch'
    #     period: 100
    #     verbose: 1
    - TensorBoard:
        extend_path: 'logs'
        update_freq: 1
    - CSVLogger:
        extend_path: 'summary/train_history.csv'
        separator: ","
        append: True
    - TrainLogger:
        extend_path: 'logs/training_log.log'
    - TrainSummary:
        extend_path: 'summary/train_summary.txt'

Test:
    data: '/home/vbpo-101386/Desktop/TuNIT/Datasets/Text Recognition/IIIT5K/test'