Dataset:
    overall:
        source_paths: "/home/vbpo-101386/Desktop/TuNIT/Datasets/Datasets/Classification/tiny_animals"
        data_type: "dirname"
        dataloader_mode: "sequence"
        sampler: ""
        load_subset: ["train", "valid"]
        color_space: "RGB"
        check_data: False
        load_memory: False

    normalizer:
        mode: "sub_divide"
        mean: null
        std: null
        interpolation: "BILINEAR"

    augmentation:
        train:
            - RandomResizeKeepRatio:
                size: 256
                longest: 0.
                random_scale_prob: 0.5
                random_scale_range: [0.08, 1.0]
                random_scale_area: True
                random_aspect_prob: 0.5
                random_aspect_range: [0.75, 1.3333333333333333]
                interpolation: "BILINEAR"
            - RandomCrop:
                size: 224
            - RandomHorizontalFlip:
            - RandomRotate:
                angle: 15
            - RandomColorJitter:
                brightness: [0.6, 1.4]
                contrast: [0.6, 1.4]
                saturation: [0.6, 1.4]
            - RandomErasing:
        valid:
            - Resize:
                size: 256
            - CenterCrop:
                size: 224
        test:
            - Resize:
                size: 256
            - CenterCrop:
                size: 224
        inference:
            - Resize:
                size: 256
            - CenterCrop:
                size: 224

Train:
    strategy:
        train_mode: "scratch"        # "scratch", "fine-tuning", "feature-extractor"
        execution_mode: "graph"          # "eager", "graph"
        compile_jit: "auto"
        checkpoints: null
        output_path: "./saved_weights/"
        model_save_mode: &model_save_mode "model"        # "weights", "model"
        model_save_head: &model_save_head True
        model_freeze_layer: -1

    hyperparams:
        batch_size: 32
        epoch:
            start: 0
            end: &end_epoch 300

    device:
        kine: "gpu"
        num_usage: [0]
        vram_usage: "growth"             # "full", "growth", "limit"
        vram_limit_mb: null
    
    advanced:
        random_seed: 0
        num_workers: 2
        mixed_precision_dtype: null
        train_with_ema: False
        sam_rho: 0.
        model_clip_gradient: 5.
        gradient_accumulation_steps: 1
        model_summary: True

Losses:
    - CategoricalCrossentropy:
        coeff: 1

Optimizer:
    name: SGD
    learning_rate: &lr 0.001
    momentum: 0.9
    nesterov: True
    weight_decay: 1.e-6
    
Metrics:
    - CategoricalAccuracy:

Callbacks:
    - Evaluate:
        sample_weight: null
        normalize_confusion_matrix: True
        min_ratio: 0.2
        save_best: True
        show_frequency: 10
    - AdvanceWarmUpLearningRate:
        lr_init: *lr
        lr_end: 1.25e-04
        epochs: *end_epoch
        warmup_epoch_ratio: 0.05 
        warmup_lr_ratio: 0.1
        no_aug_epoch_ratio: 0.05
    - LossHistory:
        save_best: False
    - MetricHistory:
        min_ratio: 0.2
        save_best: True
    - TensorBoard:
        extend_path: "logs"
        update_freq: 1
    - CSVLogger:
        extend_path: "summary/train_history.csv"
        separator: ","
        append: True
    - TrainLogger:
        extend_path: "logs/training_log.log"
    - TrainSummary:
        extend_path: "summary/train_summary.txt"
    - EarlyStopping:
        monitor: "val_loss"
        patience: 10
        verbose: 1
        mode: "min"
        restore_best_weights: True