Dataset:
    data_dir: &data_dir "/media/vbpo-101386/DATA1/Datasets/Classification/cifar10"
    annotation_dir: null
    data_info:
        data_type: 'dirname'
        color_space: &color_space 'RGB'
        check_data: False
        load_memory: False
    data_normalizer:
        norm_type: 'sub_divide'
        norm_mean: null
        norm_std: null

    data_augmentation:
        train:
            # - ResizeKeepRatio:
            #     size: 224
            #     longest: 0.
            #     interpolation: 'BILINEAR'
            #     random_scale_prob: 0.5
            #     random_scale_range: [0.08, 1.0]
            #     random_scale_area: True
            #     random_aspect_prob: 0.5
            #     random_aspect_range: [0.75, 1.3333333333333333]
            # - RandomCrop:
            #     size: 224
            # - RandomHorizontalFlip:
            # - ColorJitter:
            #     brightness: [0.6, 1.4]
            #     contrast: [0.6, 1.4]
            #     saturation: [0.6, 1.4]
            # - RandomErasing:
        valid:
            # - Resize:
            #     size: 256
            # - CenterCrop:
            #     size: 224
        test:
    data_augmentation:
    dataloader_mode: &dataloader_mode 'tf'
    get_data_mode: 2

Train:
    mode: 'graph'
    vram_usage: ""
    save_weight_path: &save_weight './saved_weights/'
    random_seed: 0
    num_workers: &num_workers 4
    batch_size: 2
    epoch:
        start: 0
        end: &end_epoch 10

Losses:
    - SparseCategoricalCrossentropy:
        coeff: 1

Optimizer:
    name: SGD
    learning_rate: &lr 0.01
    momentum: 0.937
    nesterov: True
    # weight_decay: 1.e-5
    global_clipnorm: 5.0

Metrics:
    - SparseCategoricalAccuracy:
    - SparseTopKCategoricalAccuracy:
        k: 5

Callbacks:
    - LossHistory:
        save_best: False
    - MetricHistory:
        min_ratio: 0.2
        save_best: True
    - TensorBoard:
        extend_path: 'logs'
        update_freq: 1
    - CSVLogger:
        extend_path: 'summary/train_history.csv'
        separator: ","
        append: True
    - TrainLogger:
        extend_path: 'logs/training_log.log'
    - TrainSummary:
        extend_path: 'summary/train_summary.txt'
