Model:
    inputs: [224, 224, 3]
    classes: null
    weight_path: null
    Architecture:
        name: CLS
    Backbone:
        name: RepVGG_B1
        include_head: True
        weights: null

    LoRA:
        enabled: True
        type: "lora"
        rank: 8
        alpha: 16
        dropout: 0.0
        target_layers: ["Conv2D"]
        target_names: null
        train_base: False
        train_head: True
